version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file: .env
    volumes:
      - ./pg-data-13:/var/lib/postgresql/data
    ports:
      - 5433:5432
    expose:
      - "5433"